#+ summary: Find cells by type and location
#+ description: Args: cell: the iri or a cell type; location: the iri of an anatomical location. All args are optional. With no args returns all cells with an anatomical location. Location is a union of part_of (suitable for location of most cells) and has_soma_location (used for neurons). This pattern is designed for safe grouping of cell annotations. Returns: a 2 column table: cell (type) IRIs and cell (type) labels.  

#+ defaults:
#+   - location: http://purl.obolibrary.org/obo/UBERON_0001062 # Anatomical Entity
#+   - cell: http://purl.obolibrary.org/obo/CL_0000000 # Cell

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX part_of: <http://purl.obolibrary.org/obo/BFO_0000050>
PREFIX cell: <http://purl.obolibrary.org/obo/CL_0000000>
PREFIX has_soma_location: <http://purl.obolibrary.org/obo/RO_0002100>

SELECT DISTINCT ?cell_iri (STR(?qlabel) as ?cell_label)
WHERE {
  {
    ?cell_iri part_of: ?_location_iri .
  } UNION {
    ?cell_iri has_soma_location: ?someValue .
  }
  ?cell_iri rdfs:subClassOf ?_cell_iri .
  ?cell_iri rdfs:label ?qlabel .
}

