#+ summary: List included ontologies and their version IRI

PREFIX owl: <http://www.w3.org/2002/07/owl#>
SELECT *
WHERE {
  ?ontology a owl:Ontology .
  OPTIONAL { ?ontology owl:versionIRI ?version }
}
