PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

CONSTRUCT {
  ?sub rdfs:subClassOf ?super .
}
WHERE {
  ?sub rdf:type owl:Class .
  FILTER(isIRI(?sub))
  ?sub rdfs:subClassOf* ?super .
  FILTER(isIRI(?super))
}
