name: Early warning CI
on:
  workflow_dispatch:
  schedule:
    - cron: "@daily"
jobs:
  test:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:latest
    strategy:
      max-parallel: 1
    steps:
      - uses: actions/checkout@v2
      - name: Test for incoherency
        run: ./ci/test-merged.sh
