name: Coherency check
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  test:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:latest
    strategy:
      max-parallel: 1
    steps:
      - uses: actions/checkout@v2
      - name: Test for incoherency
        run: cd ci; ./test-merged.sh
